// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3_Adriana_Kenny.web.Data;

namespace PE3_Adriana_Kenny.web.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20190511075926_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInDate");

                    b.Property<DateTime>("CheckOutDate");

                    b.Property<long>("ClientId");

                    b.Property<int>("NmbrOfPeople")
                        .HasMaxLength(1);

                    b.Property<long>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Ga je naar Colombia, dan moet je zeker een bezoek brengen aan de hoofdstad van Colombia. De hoofdstad van Colombia ligt in het midden van het land en wordt Bogota of Bogotá genoemd. Het is waarschijnlijk het eerste wat je ziet in Colombia, en dat bevalt meteen goed. Het is een gigantische stad, maar heeft leuke, sfeervolle plekjes",
                            Name = "Bogota",
                            Photo = "Bogota.jpg"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Wanneer je een bezoek aan Colombia brengt mag een bezoek aan Cartagena zeker niet ontbreken. Het is een van de bekendste steden aan de Caribische kust, een sprookjesachtige stad met romantiek, legendes en prachtig bewaard gebleven, eeuwen-oude koloniale oud centrum. Door de doolhof van geplaveide straatjes, gekleurde balkons en enorme kerken staat Cartagena op de Unesco World Heritage lijst.",
                            Name = "Cartagena",
                            Photo = "Cartagena.jpg"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Gelegen in een smalle vallei met een schitterende skyline is Medellin een van de mooist gelegen steden in Colombia. Het aangename klimaat geeft de stad zijn bijnaam – De Stad van de Eeuwige Lente",
                            Name = "Medellin",
                            Photo = "Medellin.jpg"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Colombia beschikt over verschillende eilanden.Denk bijvoorbeeld aan eilandgroepen als de Rosario - eilanden en de San Bernardo - eilanden.Ook heeft Colombia verschillende eilanden die niet direct voor de Colombiaanse kust liggen, maar wel een onderdeel van het land zijn.Een goed voorbeeld hiervan is San Andres wat in de Caribische Zee ligt",
                            Name = "San Andres",
                            Photo = "SanAndres.jpg"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Colombia beschikt over verschillende eilanden.Denk bijvoorbeeld aan eilandgroepen als de Rosario - eilanden en de San Bernardo - eilanden.Ook heeft Colombia verschillende eilanden die niet direct voor de Colombiaanse kust liggen, maar wel een onderdeel van het land zijn.Een goed voorbeeld hiervan is San Andres wat in de Caribische Zee ligt",
                            Name = "Santa Marta",
                            Photo = "SantaMarta.jpg"
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Community")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long>("CityId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NmbrOfRooms");

                    b.Property<string>("Photo");

                    b.Property<int>("Stars")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Transversal 6 No 27 - 85",
                            CityId = 1L,
                            Description = "Dit hotel ligt in Centro International, binnen 2 km afstand van Nationaal Museum en Goudmuseum. Ook Monserrate en Amerikaanse ambassade liggen binnen 5 km afstand.",
                            Name = "Ibis Bogota Museo ",
                            NmbrOfRooms = 5,
                            Photo = "IbisBogota.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Calle 95 Numero 13-35, Chapinero,",
                            CityId = 1L,
                            Description = "Selina Parque 93 Bogota ligt in Bogotá en beschikt over een terras en een gemeenschappelijke lounge. Dit 3-sterrenhotel biedt een 24-uursreceptie, een gedeelde keuken en gratis WiFi. De accommodatie is rookvrij en ligt op 2,5 km van T Zone..",
                            Name = "Selina Parque 93",
                            NmbrOfRooms = 5,
                            Photo = "SelinaParque.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Cra 71 No 69-04, Engativa",
                            CityId = 1L,
                            Description = "Deportel Bogotá ligt op 100 m van het La Europa Park en op 3 km van hetSimón Bolívar Park. Het beschikt over een gemeenschappelijke lounge en gratis WiFi in alle ruimtes.",
                            Name = "Deportel Bogotá",
                            NmbrOfRooms = 5,
                            Photo = "Deportel.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Avenida Carrera 7 # 69a-22, Chapinero",
                            CityId = 1L,
                            Description = "Ga voor een sterrenbehandeling en geniet van service van wereldklasse in Four Seasons Hotel Casa Medina Bogotavan T Zone..",
                            Name = "Four Seasons Hotel Casa Medina",
                            NmbrOfRooms = 5,
                            Photo = "FourSeasonsCasaMedina",
                            Stars = 3
                        },
                        new
                        {
                            Id = 5L,
                            Address = "Avenida Carrera 7 # 69a-22, Chapinero",
                            CityId = 1L,
                            Description = " Een van onze bestsellers in Bogota!Expo Suites Parque Central Bavaria ligt in de financiële wijk van Bogotá.Het biedt een trendy,paars interieur met witte orchideeën en kamers met gratis WiFi.",
                            Name = "Expo Suites Parque Bavaria",
                            NmbrOfRooms = 5,
                            Photo = "ExpoSuitesParque",
                            Stars = 3
                        },
                        new
                        {
                            Id = 6L,
                            Address = "Calle 34 # 11-15. Plazoleta Telecom, La Matuna",
                            CityId = 2L,
                            Description = "Hotel Stil biedt ruime accommodatie met gratis WiFi en een pendeldienst van/naar de luchthaven. Het ligt in het historische centrum van Cartagena, dicht bij India Catalina in het traditionele stadsdeel La Matuta.",
                            Name = "Hotel Stil Cartagena",
                            NmbrOfRooms = 5,
                            Photo = "StilCartagena.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 7L,
                            Address = "Bocagrande, Avenida 1A # Calle 9A Esquina, Bocagrande",
                            CityId = 2L,
                            Description = "Costa del Sol ligt aan het strand van Bocagrande. De accommodatie biedt gratis WiFi en een zwembad op het dak met panoramisch uitzicht op de baai en de ommuurde stad Cartagena.",
                            Name = "Hotel Costa del Sol",
                            NmbrOfRooms = 5,
                            Photo = "CostaDelSol.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 8L,
                            Address = "Calle 5 # 3 14 Bocagrande, Bocagrande,",
                            CityId = 2L,
                            Description = "Hotel Zi One in Cartagena de Indias beschikt over een buitenbad en kamers met gratis WiFi en uitzicht op zee. De 4-sterrenaccommodatie ligt op 2,8 km van het Paleis van de Inquisitie, het Goudmuseum van Cartagena en het Bolivar-park.",
                            Name = "Hotel Zi One Luxury",
                            NmbrOfRooms = 5,
                            Photo = "ZiOneLuxury.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 9L,
                            Address = "Bocagrande, Carrera. 1a # 2-87, Bocagrande",
                            CityId = 2L,
                            Description = "Dit luxueuze hotel aan het Caribische strand heeft een buitenzwembad, stijlvolle koloniale architectuur en spafaciliteiten. U kunt massages en duiktrips reserveren. WiFi is gratis beschikbaar.",
                            Name = "Hotel Caribe By Faranda",
                            NmbrOfRooms = 5,
                            Photo = "CaribeByFaranda.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 10L,
                            Address = "Centro historico, Calle del Sargento No. 6 - 87, Centro",
                            CityId = 2L,
                            Description = "Dit moderne hotel ligt in het hart van de ommuurde stad Cartagena. Het bevindt zich in een gerenoveerd gebouw uit de 16e eeuw en beschikt over een dakterras met een zwembad en een gedeelde woonkamer. Het beschikt ook over een eigen gastronomisch restaurant en gratis WiFi.",
                            Name = "Bastión Luxury Hotel",
                            NmbrOfRooms = 5,
                            Photo = "BastionLuxury.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 21L,
                            Address = "Calle 16 # 5-17, Centro Histórico",
                            CityId = 5L,
                            Description = "Hotel Catedral Plaza ligt in Santa Marta in de regio Magdalena, op 5 km van het strand van El Rodadero. Het beschikt over een buitenbad en een zonneterras. Gasten kunnen genieten van de bar bij de accommodatie, en er wordt dagelijks een Amerikaans ontbijt aangeboden.",
                            Name = "Hotel Catedral Plaza",
                            NmbrOfRooms = 5,
                            Photo = "CatedralPlaza.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 22L,
                            Address = "Km 17 vía a Cienaga",
                            CityId = 5L,
                            Description = "Het hotel ligt op slechts 100 meter van het strand van Pozos Colorados en beschikt over een zwembad, 2 tennisbanen en een discobar. U kunt dineren in een restaurant in de vorm van een piratenschip.",
                            Name = "Decameron Galeon",
                            NmbrOfRooms = 5,
                            Photo = "DecameronGaleon.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 23L,
                            Address = "Km 14 via a Cienaga. Bello Horizonte",
                            CityId = 5L,
                            Description = "Het Irotama Resort ligt op 100 meter van het strand en biedt op het terrein zelf watersportactiviteiten, 3 buitenzwembaden en een spa- en fitnesscentrum. Er is WiFi beschikbaar. Er worden ook activiteiten voor kinderen georganiseerd. Er is bovendien gratis vervoer vanaf de luchthaven mogelijk.",
                            Name = "Irotama Resort",
                            NmbrOfRooms = 5,
                            Photo = "IrotamaResort.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 24L,
                            Address = "Calle 11a No 6-136, El Rodadero, Cerro la Llorona",
                            CityId = 5L,
                            Description = "Bunsizanisi Hotel ligt in de wijk El Rodadero van Santa Marta en beschikt over kamers met gratis WiFi. Tot de verschillende faciliteiten van deze accommodatie behoren een buitenzwembad, een tuin en een terras. De accommodatie ligt op 700 m van het strand El Rodadero.",
                            Name = "Bunsizanisi Hotel",
                            NmbrOfRooms = 5,
                            Photo = "Bunsizanisi.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 25L,
                            Address = "Carrera 1C No. 24-04",
                            CityId = 5L,
                            Description = "Hilton Garden Inn Santa Marta bevindt zich in Santa Marta, en biedt een buitenzwembad, een fitnesscentrum, een tuin en gratis WiFi. De accommodatie ligt op 6 km van het strand van El Rodadero, op 200 meter van de jachthaven van Santa Marta en op 1 km van de kathedraal van Santa Marta. Het hotel beschikt over een gemeenschappelijke lounge.",
                            Name = "Hilton Garden Inn Santa Marta",
                            NmbrOfRooms = 5,
                            Photo = "HiltonGardenInn.jpg",
                            Stars = 4
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<long>("HotelId");

                    b.Property<decimal>("PriceNight");

                    b.Property<long>("RoomtypeId");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomtypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Roomtype", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roomtypes");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotel", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Room", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Roomtype", "Roomtype")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomtypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
