// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3_Adriana_Kenny.web.Data;

namespace PE3_Adriana_Kenny.web.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInDate");

                    b.Property<DateTime>("CheckOutDate");

                    b.Property<long>("ClientId");

                    b.Property<int>("NmbrOfPeople")
                        .HasMaxLength(1);

                    b.Property<long>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Photo");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Ga je naar Colombia, dan moet je zeker een bezoek brengen aan de hoofdstad van Colombia. De hoofdstad van Colombia ligt in het midden van het land en wordt Bogota of Bogotá genoemd. Het is waarschijnlijk het eerste wat je ziet in Colombia, en dat bevalt meteen goed. Het is een gigantische stad, maar heeft leuke, sfeervolle plekjes",
                            Name = "Bogota",
                            Photo = "Bogota.jpg"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Wanneer je een bezoek aan Colombia brengt mag een bezoek aan Cartagena zeker niet ontbreken. Het is een van de bekendste steden aan de Caribische kust, een sprookjesachtige stad met romantiek, legendes en prachtig bewaard gebleven, eeuwen-oude koloniale oud centrum. Door de doolhof van geplaveide straatjes, gekleurde balkons en enorme kerken staat Cartagena op de Unesco World Heritage lijst.",
                            Name = "Cartagena",
                            Photo = "Cartagena.jpg"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Gelegen in een smalle vallei met een schitterende skyline is Medellin een van de mooist gelegen steden in Colombia. Het aangename klimaat geeft de stad zijn bijnaam – De Stad van de Eeuwige Lente",
                            Name = "Medellin",
                            Photo = "Medellin.jpg"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Colombia beschikt over verschillende eilanden.Denk bijvoorbeeld aan eilandgroepen als de Rosario - eilanden en de San Bernardo - eilanden.Ook heeft Colombia verschillende eilanden die niet direct voor de Colombiaanse kust liggen, maar wel een onderdeel van het land zijn.Een goed voorbeeld hiervan is San Andres wat in de Caribische Zee ligt",
                            Name = "San Andres",
                            Photo = "SanAndres.jpg"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Santa Marta is een belangrijke havenstad in Colombia, maar ook reizigers mogen de stad zeker niet overslaan. Santa Marta is namelijk de perfecte uitvalsbasis om de diversiteit van de Caribische kust te ontdekken. Om te dwalen in de groene jungle en te relaxen aan de paradijselijke stranden. De stad ligt namelijk niet alleen aan de noordelijke kust, maar ook aan de voet van het gebergte Sierra Nevada de Santa Marta.",
                            Name = "Santa Marta",
                            Photo = "SantaMarta.jpg"
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Community")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<long>("CityId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Facilities");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NmbrOfRooms");

                    b.Property<string>("Photo");

                    b.Property<int>("Stars")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Transversal 6 No 27 - 85",
                            CityId = 1L,
                            Description = "Dit hotel ligt in Centro International, binnen 2 km afstand van Nationaal Museum en Goudmuseum. Ook Monserrate en Amerikaanse ambassade liggen binnen 5 km afstand.",
                            Facilities = "Gratis wifi, rookvrije kamers,24-uursreceptie,bar,goed ontbijt",
                            Name = "Ibis Bogota Museo ",
                            NmbrOfRooms = 5,
                            Photo = "IbisBogota.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Calle 95 Numero 13-35, Chapinero,",
                            CityId = 1L,
                            Description = "Selina Parque 93 Bogota ligt in Bogotá en beschikt over een terras en een gemeenschappelijke lounge. Dit 3-sterrenhotel biedt een 24-uursreceptie, een gedeelde keuken en gratis WiFi. De accommodatie is rookvrij en ligt op 2,5 km van T Zone..",
                            Facilities = "Gratis wifi, rookvrije kamers,restaurant,bar,goed ontbijt",
                            Name = "Selina Parque 93",
                            NmbrOfRooms = 5,
                            Photo = "SelinaParque.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Cra 71 No 69-04, Engativa",
                            CityId = 1L,
                            Description = "Deportel Bogotá ligt op 100 m van het La Europa Park en op 3 km van hetSimón Bolívar Park. Het beschikt over een gemeenschappelijke lounge en gratis WiFi in alle ruimtes.",
                            Facilities = "Gratis wifi, rookvrije kamers,24-uursreceptie,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Deportel Bogotá",
                            NmbrOfRooms = 5,
                            Photo = "Deportel.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Avenida Carrera 7 # 69a-22, Chapinero",
                            CityId = 1L,
                            Description = "Ga voor een sterrenbehandeling en geniet van service van wereldklasse in Four Seasons Hotel Casa Medina Bogotavan T Zone..",
                            Facilities = "Gratis wifi, luchthavenshuttle,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Four Seasons Hotel Casa Medina",
                            NmbrOfRooms = 5,
                            Photo = "FourSeasonsCasaMedina.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 5L,
                            Address = "Avenida Carrera 7 # 69a-22, Chapinero",
                            CityId = 1L,
                            Description = " Een van onze bestsellers in Bogota!Expo Suites Parque Central Bavaria ligt in de financiële wijk van Bogotá.Het biedt een trendy,paars interieur met witte orchideeën en kamers met gratis WiFi.",
                            Facilities = "Gratis wifi, rookvrije kamers,24-uursreceptie,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Expo Suites Parque Bavaria",
                            NmbrOfRooms = 5,
                            Photo = "ExpoSuitesParque.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 6L,
                            Address = "Calle 34 # 11-15. Plazoleta Telecom, La Matuna",
                            CityId = 2L,
                            Description = "Hotel Stil biedt ruime accommodatie met gratis WiFi en een pendeldienst van/naar de luchthaven. Het ligt in het historische centrum van Cartagena, dicht bij India Catalina in het traditionele stadsdeel La Matuta.",
                            Facilities = "Gratis wifi, rookvrije kamers,24-uursreceptie,bar,restaurant,airconditioning,goed ontbijt",
                            Name = "Hotel Stil Cartagena",
                            NmbrOfRooms = 5,
                            Photo = "StilCartagena.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 7L,
                            Address = "Bocagrande, Avenida 1A # Calle 9A Esquina, Bocagrande",
                            CityId = 2L,
                            Description = "Costa del Sol ligt aan het strand van Bocagrande. De accommodatie biedt gratis WiFi en een zwembad op het dak met panoramisch uitzicht op de baai en de ommuurde stad Cartagena.",
                            Facilities = "Gratis wifi, rookvrije kamers,24-uursreceptie,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Hotel Costa del Sol",
                            NmbrOfRooms = 5,
                            Photo = "CostaDelSol.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 8L,
                            Address = "Calle 5 # 3 14 Bocagrande, Bocagrande,",
                            CityId = 2L,
                            Description = "Hotel Zi One in Cartagena de Indias beschikt over een buitenbad en kamers met gratis WiFi en uitzicht op zee. De 4-sterrenaccommodatie ligt op 2,8 km van het Paleis van de Inquisitie, het Goudmuseum van Cartagena en het Bolivar-park.",
                            Facilities = "Gratis wifi, rookvrije kamers,bar,restaurant,wasservice,airconditioning,goed ontbijt",
                            Name = "Hotel Zi One Luxury",
                            NmbrOfRooms = 5,
                            Photo = "ZiOneLuxury.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 9L,
                            Address = "Bocagrande, Carrera. 1a # 2-87, Bocagrande",
                            CityId = 2L,
                            Description = "Dit luxueuze hotel aan het Caribische strand heeft een buitenzwembad, stijlvolle koloniale architectuur en spafaciliteiten. U kunt massages en duiktrips reserveren. WiFi is gratis beschikbaar.",
                            Facilities = "Gratis wifi, luchthavenshuttle,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Hotel Caribe By Faranda",
                            NmbrOfRooms = 5,
                            Photo = "CaribeByFaranda.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 10L,
                            Address = "Centro historico, Calle del Sargento No. 6 - 87, Centro",
                            CityId = 2L,
                            Description = "Dit moderne hotel ligt in het hart van de ommuurde stad Cartagena. Het bevindt zich in een gerenoveerd gebouw uit de 16e eeuw en beschikt over een dakterras met een zwembad en een gedeelde woonkamer. Het beschikt ook over een eigen gastronomisch restaurant en gratis WiFi.",
                            Facilities = "Gratis wifi, luchthavenshuttle,bar,restaurant,gratis parkeergelegenheid,goed ontbijt",
                            Name = "Bastión Luxury Hotel",
                            NmbrOfRooms = 5,
                            Photo = "BastionLuxury.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 11L,
                            Address = "Carrera 42 A No. 1 - 15, El Poblado, Medellín",
                            CityId = 3L,
                            Description = "San Fernando Plaza beschikt over een verwarmd buitenzwembad, een spa en een fitnesscentrum.Het biedt luxe accommodatie in El Poblado, de exclusieve financiële en commerciële wijk van Medellin.Het hotel heeft ook een restaurant en een bar.",
                            Facilities = "Gratis wifi, luchthavenshuttle,bar,restaurant,airconditioning,goed ontbijt",
                            Name = "Hotel San Fernando Plaza",
                            NmbrOfRooms = 5,
                            Photo = "SanFernandoPlaza.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 12L,
                            Address = "Carrera 45 # 49-35, La Candelaria, Medellín.",
                            CityId = 3L,
                            Description = "Hotel Suite 45 ligt in Medellin, op slechts 1 km van het metrostation Parque Berrio en biedt kamers met gratis WiFi en kabel-tv. Bij de accommodatie is gratis parkeergelegenheid beschikbaar. Het centrale plein en het Botero-plein liggen op 1 km afstand.",
                            Facilities = "Gratis wifi,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Hotel Suite 45",
                            NmbrOfRooms = 5,
                            Photo = "Suite45.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 13L,
                            Address = "3324 Carrera 65, Laureles, Medellín",
                            CityId = 3L,
                            Description = "Hotel Medellin 33 ligt op 2,9 km van Pueblito Paisa, in Medellín.Het biedt een aantal voorzieningen, waaronder een buitenzwembad, een fitnesscentrum en een terras.Tot de faciliteiten van deze accommodatie behoren een restaurant, een 24 - uursreceptie, een gemeenschappelijke lounge en gratis WiFi. De accommodatie beschikt over een hot tub, entertainmentpersoneel en roomservice.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Hotel Medellin 33",
                            NmbrOfRooms = 5,
                            Photo = "Medellin33.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 14L,
                            Address = "Carrera 32d # 9-17, El Poblado, Medellín.",
                            CityId = 3L,
                            Description = "Selina Medellin ligt in Medellín en biedt een terras, een gemeenschappelijke lounge, een restaurant, een 24 - uursreceptie, een gemeenschappelijke keuken en gratis WiFi. Voor een drankje kunt u terecht bij de bar.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,wasservice,goed ontbijt",
                            Name = "Selina Medellin",
                            NmbrOfRooms = 5,
                            Photo = "SelinaMedellin.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 15L,
                            Address = "CR 69 46B 34, Laureles, Medellín.",
                            CityId = 3L,
                            Description = "Mooie, schone kamers met een moderne badkamer. Op loopafstand van het metrostation en om de hoek van een gezellige uitgaansstraat in Medellin met leuke restaurants e.d.waar weinig toeristen komen en je dus meer tussen de locals zit. Top locatie!",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,wasservice,goed ontbijt",
                            Name = "HOTEL MED 70",
                            NmbrOfRooms = 5,
                            Photo = "Med70.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 16L,
                            Address = "Av. 20 de Julio Nº 3A - 122, San Andrés.",
                            CityId = 4L,
                            Description = "San Andrés Hostel heeft kamers met airconditioning.Het ligt op slechts 5 minuten lopen van het strand en de zee van 7 kleuren.Er is een discobar bij de accommodatie en er zijn duiklessen beschikbaar. ",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,wasservice,goed ontbijt",
                            Name = "Viajero San Andres Hostel",
                            NmbrOfRooms = 5,
                            Photo = "ViajeroSanandresHostel.jpg ",
                            Stars = 4
                        },
                        new
                        {
                            Id = 17L,
                            Address = "Calle 3 18 - 71 , San Andrés.",
                            CityId = 4L,
                            Description = "Deze elegante villa in mediterrane stijl heeft een buitenzwembad.U kunt er verblijven in kamers met airconditioning en gratis WiFi. Er is ook gratis privéparkeergelegenheid beschikbaar.",
                            Facilities = "Gratis wifi,luchthavenshuttle,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,wasservice,goed ontbijt",
                            Name = "Le Castel Blanc Hotel Boutique",
                            NmbrOfRooms = 5,
                            Photo = "LeCastelBlanc.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 18L,
                            Address = "Vía a San Luis # 43-39, San Andrés.",
                            CityId = 4L,
                            Description = "Hotel Cocoplum Beach ligt aan het Cocoplum - strand, een van de mooiste stranden van San Andrés. Het biedt een zwembad, een spa en een restaurant met uitzicht op zee. Er is gratis WiFi beschikbaar in de gemeenschappelijke ruimtes en het hotel serveert ontbijt.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,gratis parkeergelegenheid,goed ontbijt",
                            Name = "Hotel Cocoplum Beach",
                            NmbrOfRooms = 5,
                            Photo = "CocoplumBeach.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 19L,
                            Address = "Via San Luis, Antes de Rocky Cay Bay,  San Andrés.",
                            CityId = 4L,
                            Description = "San Luis Place By El Dorado ligt in San Andrés, in de omgeving van de eilanden San Andres en Providencia, op nog geen 3,5 km van San Andrés-baai, en beschikt over een zonneterras en een eigen strand.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,airconditioning,goed ontbijt",
                            Name = "San Luis Place By El Dorado",
                            NmbrOfRooms = 5,
                            Photo = "ElDorado.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 20L,
                            Address = "Via san luis, 880001 San Andrés.",
                            CityId = 4L,
                            Description = "Hostal Rohomar biedt gratis WiFi en uitzicht op zee in San Andrés. Het pension ligt op ongeveer 2,6 km van de baai van San Andres en op 3,5 km van North End. Lokale bezienswaardigheden zoals Spratt Bight en The Hill zijn bereikbaar binnen respectievelijk 3,7 km en 1,9 km.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,gratis parkeergelegenheid,wasservice,goed ontbijt",
                            Name = "Hostal Rohomar",
                            NmbrOfRooms = 5,
                            Photo = "HostalRohomar.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 21L,
                            Address = "Calle 16 # 5-17, Centro Histórico",
                            CityId = 5L,
                            Description = "Hotel Catedral Plaza ligt in Santa Marta in de regio Magdalena, op 5 km van het strand van El Rodadero. Het beschikt over een buitenbad en een zonneterras. Gasten kunnen genieten van de bar bij de accommodatie, en er wordt dagelijks een Amerikaans ontbijt aangeboden.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenhei,goed ontbijt",
                            Name = "Hotel Catedral Plaza",
                            NmbrOfRooms = 5,
                            Photo = "CatedralPlaza.jpg",
                            Stars = 4
                        },
                        new
                        {
                            Id = 22L,
                            Address = "Km 17 vía a Cienaga",
                            CityId = 5L,
                            Description = "Het hotel ligt op slechts 100 meter van het strand van Pozos Colorados en beschikt over een zwembad, 2 tennisbanen en een discobar. U kunt dineren in een restaurant in de vorm van een piratenschip.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,wasservice,goed ontbijt",
                            Name = "Decameron Galeon",
                            NmbrOfRooms = 5,
                            Photo = "DecameronGaleon.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 23L,
                            Address = "Km 14 via a Cienaga. Bello Horizonte",
                            CityId = 5L,
                            Description = "Het Irotama Resort ligt op 100 meter van het strand en biedt op het terrein zelf watersportactiviteiten, 3 buitenzwembaden en een spa- en fitnesscentrum. Er is WiFi beschikbaar. Er worden ook activiteiten voor kinderen georganiseerd. Er is bovendien gratis vervoer vanaf de luchthaven mogelijk.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,wasservice,luchthavenshuttle,goed ontbijt",
                            Name = "Irotama Resort",
                            NmbrOfRooms = 5,
                            Photo = "IrotamaResort.jpg",
                            Stars = 5
                        },
                        new
                        {
                            Id = 24L,
                            Address = "Calle 11a No 6-136, El Rodadero, Cerro la Llorona",
                            CityId = 5L,
                            Description = "Bunsizanisi Hotel ligt in de wijk El Rodadero van Santa Marta en beschikt over kamers met gratis WiFi. Tot de verschillende faciliteiten van deze accommodatie behoren een buitenzwembad, een tuin en een terras. De accommodatie ligt op 700 m van het strand El Rodadero.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,wasservice,goed ontbijt",
                            Name = "Bunsizanisi Hotel",
                            NmbrOfRooms = 5,
                            Photo = "Bunsizanisi.jpg",
                            Stars = 3
                        },
                        new
                        {
                            Id = 25L,
                            Address = "Carrera 1C No. 24-04",
                            CityId = 5L,
                            Description = "Hilton Garden Inn Santa Marta bevindt zich in Santa Marta, en biedt een buitenzwembad, een fitnesscentrum, een tuin en gratis WiFi. De accommodatie ligt op 6 km van het strand van El Rodadero, op 200 meter van de jachthaven van Santa Marta en op 1 km van de kathedraal van Santa Marta. Het hotel beschikt over een gemeenschappelijke lounge.",
                            Facilities = "Gratis wifi,rookvrije kamers,bar,restaurant,gratis parkeergelegenheid,zwembad,goed ontbijt",
                            Name = "Hilton Garden Inn Santa Marta",
                            NmbrOfRooms = 5,
                            Photo = "HiltonGardenInn.jpg",
                            Stars = 4
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<long>("HotelId");

                    b.Property<decimal>("PriceNight");

                    b.Property<long>("RoomTypeId");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Deze suite heeft een balkon een eigen ingang en een zithoek.",
                            HotelId = 1L,
                            PriceNight = 80m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Deze suite heeft een balkon, een eigen ingang en een zithoek.",
                            HotelId = 1L,
                            PriceNight = 80m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.",
                            HotelId = 1L,
                            PriceNight = 50m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.",
                            HotelId = 1L,
                            PriceNight = 50m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer.",
                            HotelId = 1L,
                            PriceNight = 65m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Deze suite heeft een balkon, een eigen ingang en een zithoek",
                            HotelId = 2L,
                            PriceNight = 90m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.",
                            HotelId = 2L,
                            PriceNight = 40m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.",
                            HotelId = 2L,
                            PriceNight = 40m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer.",
                            HotelId = 2L,
                            PriceNight = 60m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer.",
                            HotelId = 2L,
                            PriceNight = 60m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.",
                            HotelId = 3L,
                            PriceNight = 60m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer ",
                            HotelId = 3L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 13L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer",
                            HotelId = 3L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 3L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 3L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 16L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek",
                            HotelId = 4L,
                            PriceNight = 80m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer ",
                            HotelId = 4L,
                            PriceNight = 55m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 18L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer",
                            HotelId = 4L,
                            PriceNight = 55m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 19L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 4L,
                            PriceNight = 65m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 4L,
                            PriceNight = 65m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 21L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 5L,
                            PriceNight = 95m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Description = "Deze suite heeft een balkon, een eigen ingang en een zithoek ",
                            HotelId = 5L,
                            PriceNight = 95m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer",
                            HotelId = 5L,
                            PriceNight = 65m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 24L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 5L,
                            PriceNight = 75m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 25L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer",
                            HotelId = 5L,
                            PriceNight = 75m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 26L,
                            Description = "Deze suite heeft een balkon,een betegelde / marmeren vloer en airconditioning",
                            HotelId = 6L,
                            PriceNight = 100m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 27L,
                            Description = "Deze suite heeft een balkon, een eigen ingang en een zithoek en  airconditioning ",
                            HotelId = 6L,
                            PriceNight = 90m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning",
                            HotelId = 6L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 29L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning",
                            HotelId = 6L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 30L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 6L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 31L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 7L,
                            PriceNight = 110m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 32L,
                            Description = "Deze suite heeft een balkon, een eigen ingang en een zithoek en airconditioning.",
                            HotelId = 7L,
                            PriceNight = 95m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 33L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning.",
                            HotelId = 7L,
                            PriceNight = 75m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 34L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning.",
                            HotelId = 7L,
                            PriceNight = 85m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 35L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning.",
                            HotelId = 7L,
                            PriceNight = 85m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 36L,
                            Description = "Deze suite heeft een balkon,een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 8L,
                            PriceNight = 100m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 37L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 8L,
                            PriceNight = 100m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 38L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning",
                            HotelId = 8L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 39L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek,airconditioning en een betegelde / marmeren vloer  airconditioning",
                            HotelId = 8L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning.",
                            HotelId = 8L,
                            PriceNight = 80m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 9L,
                            PriceNight = 90m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 42L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 9L,
                            PriceNight = 70m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 43L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning.",
                            HotelId = 9L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 44L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 9L,
                            PriceNight = 85m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 45L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 9L,
                            PriceNight = 85m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 46L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 10L,
                            PriceNight = 105m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 47L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 10L,
                            PriceNight = 80m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 48L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning.",
                            HotelId = 10L,
                            PriceNight = 70m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 49L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 10L,
                            PriceNight = 90m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 50L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 10L,
                            PriceNight = 90m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 51L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 11L,
                            PriceNight = 95m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 52L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 11L,
                            PriceNight = 85m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 53L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 11L,
                            PriceNight = 50m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 54L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 11L,
                            PriceNight = 70m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 55L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 11L,
                            PriceNight = 70m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 56L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 12L,
                            PriceNight = 80m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 57L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 12L,
                            PriceNight = 80m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 58L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer airconditioning.",
                            HotelId = 12L,
                            PriceNight = 45m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 59L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 12L,
                            PriceNight = 60m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 60L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 12L,
                            PriceNight = 70m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 61L,
                            Description = "Deze suite heeft een balkon,een eigen ingang en een zithoek.",
                            HotelId = 13L,
                            PriceNight = 85m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 62L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden,betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 13L,
                            PriceNight = 60m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 63L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden ,betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 13L,
                            PriceNight = 60m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 64L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 13L,
                            PriceNight = 75m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 65L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 13L,
                            PriceNight = 75m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 66L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 14L,
                            PriceNight = 85m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 67L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 14L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 68L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 14L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 69L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 14L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 70L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 14L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 71L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 15L,
                            PriceNight = 55m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 72L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning.",
                            HotelId = 15L,
                            PriceNight = 90m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 73L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 15L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 74L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 15L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 75L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 15L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 76L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 16L,
                            PriceNight = 45m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 77L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning.",
                            HotelId = 16L,
                            PriceNight = 45m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 78L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 16L,
                            PriceNight = 50m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 79L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 16L,
                            PriceNight = 70m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 80L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 16L,
                            PriceNight = 70m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 81L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 17L,
                            PriceNight = 140m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 82L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning.",
                            HotelId = 17L,
                            PriceNight = 70m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 83L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 17L,
                            PriceNight = 75m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 84L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 17L,
                            PriceNight = 90m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 85L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 17L,
                            PriceNight = 90m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 86L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 18L,
                            PriceNight = 150m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 87L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 18L,
                            PriceNight = 120m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 88L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 18L,
                            PriceNight = 75m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 89L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 18L,
                            PriceNight = 95m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 90L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 18L,
                            PriceNight = 95m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 91L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 19L,
                            PriceNight = 120m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 92L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 19L,
                            PriceNight = 100m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 93L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 19L,
                            PriceNight = 85m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 94L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 19L,
                            PriceNight = 95m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 95L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 19L,
                            PriceNight = 95m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 96L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 20L,
                            PriceNight = 180m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 97L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 20L,
                            PriceNight = 150m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 98L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 20L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 99L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 20L,
                            PriceNight = 110m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 100L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 20L,
                            PriceNight = 110m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 101L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 21L,
                            PriceNight = 150m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 102L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 21L,
                            PriceNight = 130m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 103L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 21L,
                            PriceNight = 80m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 104L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 21L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 105L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 21L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 106L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 22L,
                            PriceNight = 170m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 107L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 22L,
                            PriceNight = 150m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 108L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 22L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 109L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer  airconditioning ",
                            HotelId = 22L,
                            PriceNight = 105m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 110L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 22L,
                            PriceNight = 105m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 111L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 23L,
                            PriceNight = 160m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 112L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 23L,
                            PriceNight = 90m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 113L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 23L,
                            PriceNight = 100m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 114L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning ",
                            HotelId = 23L,
                            PriceNight = 90m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 115L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 23L,
                            PriceNight = 110m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 116L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 24L,
                            PriceNight = 130m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 117L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning",
                            HotelId = 24L,
                            PriceNight = 80m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 118L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 24L,
                            PriceNight = 80m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 119L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning ",
                            HotelId = 24L,
                            PriceNight = 80m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 120L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 24L,
                            PriceNight = 100m,
                            RoomTypeId = 4L
                        },
                        new
                        {
                            Id = 121L,
                            Description = "Deze suite heeft een balkon, een betegelde / marmeren vloer en airconditioning.",
                            HotelId = 25L,
                            PriceNight = 160m,
                            RoomTypeId = 1L
                        },
                        new
                        {
                            Id = 122L,
                            Description = "Deze suite heeft een balkon,een eigen ingang, een zithoek en airconditioning",
                            HotelId = 25L,
                            PriceNight = 140m,
                            RoomTypeId = 2L
                        },
                        new
                        {
                            Id = 123L,
                            Description = "Tweepersoonskamer met 2 eenpersoonsbedden, betegelde / marmeren vloeren en een kitchenette met keukengerei.Gedeelde badkamer.",
                            HotelId = 25L,
                            PriceNight = 90m,
                            RoomTypeId = 5L
                        },
                        new
                        {
                            Id = 124L,
                            Description = "Tweepersoonskamer met betegelde / marmeren vloeren en een kitchenette met keukengerei en airconditioning ",
                            HotelId = 25L,
                            PriceNight = 90m,
                            RoomTypeId = 3L
                        },
                        new
                        {
                            Id = 125L,
                            Description = "Deze driepersoonskamer is voorzien van een zithoek, airconditioning en een betegelde / marmeren vloer airconditioning",
                            HotelId = 25L,
                            PriceNight = 110m,
                            RoomTypeId = 4L
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Roomtype", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxPersoons");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roomtypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MaxPersoons = 2,
                            Type = "Suite met Uitzicht op Zee"
                        },
                        new
                        {
                            Id = 2L,
                            MaxPersoons = 2,
                            Type = "Suite"
                        },
                        new
                        {
                            Id = 3L,
                            MaxPersoons = 2,
                            Type = "Tweepersoonskamer"
                        },
                        new
                        {
                            Id = 4L,
                            MaxPersoons = 3,
                            Type = "Driepersoonskamer"
                        },
                        new
                        {
                            Id = 5L,
                            MaxPersoons = 2,
                            Type = "Tweepersoonskamer met 2 aparte bedden"
                        });
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotel", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Room", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Roomtype", "Roomtype")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
