// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3_Adriana_Kenny.web.Data;

namespace PE3_Adriana_Kenny.web.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BookingId");

                    b.Property<DateTime>("CheckInDate");

                    b.Property<DateTime>("CheckOutDate");

                    b.Property<long?>("ClientBookingId");

                    b.Property<long>("CustomerId");

                    b.Property<int>("NmbrOfPeople")
                        .HasMaxLength(1);

                    b.Property<long>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClientBookingId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Community")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Surname");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotels", b =>
                {
                    b.Property<long>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("CityId");

                    b.Property<long?>("CityId1");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("NmbrOfRooms");

                    b.Property<string>("Photo");

                    b.Property<int>("Stars");

                    b.HasKey("HotelId");

                    b.HasIndex("CityId1");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("HotelId");

                    b.Property<decimal>("PriceNight");

                    b.Property<long>("RoomTypeId");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Roomtype", b =>
                {
                    b.Property<long>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("RoomTypeId");

                    b.ToTable("Roomtypes");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Booking", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Booking")
                        .WithMany("RoomBookings")
                        .HasForeignKey("BookingId");

                    b.HasOne("PE3_Adriana_Kenny.web.Entities.Client", "ClientBooking")
                        .WithMany("ClientBookings")
                        .HasForeignKey("ClientBookingId");
                });

            modelBuilder.Entity("PE3_Adriana_Kenny.web.Entities.Hotels", b =>
                {
                    b.HasOne("PE3_Adriana_Kenny.web.Entities.City")
                        .WithMany("StadHotels")
                        .HasForeignKey("CityId1");
                });
#pragma warning restore 612, 618
        }
    }
}
